version: '{build}'

environment:
  matrix:
    - ANDROID_HOME: 'C:\android-sdk-windows'

skip_tags: true
branches:
  only:
    - master


install:
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
  - 7z x sdk-tools-windows-4333796.zip -oC:\android-sdk-windows > nul
  - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses

build_script:
  - cmd: set KEYSTORE_RELEASE=publicKeyStore.keystore
  - cmd: set KEYSTORE_DEBUG=debug.keystore
  - cmd: set KEYSTORE_PASSWORD=YiBODrehfLo37Mm5f3BFMASXRawiWXMj23RDZRRqBFul7TCvyWbqA2oeRR26CbIAnxiivjfWKyjP5aEbzabImmthxjNmewVUztP2sDyRuLPHjWnBYFzSwclAUecDxL8Vs5iOb2ds1h8XzfRFyOfKLZYrlsF9FI6AX10nspgcHs92Y28DoiN44hGkuLnPBk0PcEbeEsy5c3iWCz2bNolkdcjCaNJAZgjUUY48OyC9aJIujAFb4fNavxq24tznW70G63X6cRbuf0bhXtzVL2g39FXuhCKERcgu5dCbgp554mJbw2nL7XK7bK71HMkeBHk00huRSxN6hAKpd6uM2v65Ywd79lc42WHCaafPmoYTosBTvJSIcAKF64gpZCjCKCH6XwJyqAY3Mbp1T1QXyKor7WTvQmkF6Bjxux3TV3q4rf3roSbc96d2Qpy5hBWo0MiHNbFL0U9UwFJXzo0xXxNeFB2i285mq1kBBOvIEeYhsLhkGwX6craNEZu3DzjeHZRS
  - cmd: set KEY_ALIAS=publicKey
  - cmd: set KEY_PASSWORD=Xmg4oe1rydYZvIlDLzY5OSFDJkf2zIJcXhclCy0SeqMzGchDOsZf4w4AJANzC5D2LVltlF0onOQkBetHKMW5uEsbyFoZOVT9RhZr7NuTtafBLAVK1XDokHbCfQwUxqp2yGsnEyG8WU0fu8BRtdhce58KkoqrWuaA3uSb6h5IOjXU8TOhu1xcyHQ6IVDrsipK3FjLEU1u2rOY6ZZcaRNuYWQYWFh7DppXSYvhAxD23ckXqpyaVqHHHFyeV1SQTnp2oXIxB3jiyKETIlQN8z4gWyly05r8ZP84MrCE2dOt3buR0H5yIR6RPqVQc21B4tBKvk5g1NxT5qASaOFSRwMrCdd6B9rfmlX6iGtGLfaSRbGCeVzJOsMynps3U25IJ2S6UBD8eifCriyi9R3zmEhk6c46JBVfnZLRTQpDE1XobS7lCvf2t2aGW94ecBL6OILr9YaY9hEbEvD1JJegHjXepV74Hc19yAOS44WMBngWg79KHn4pvTnhffbH2bui3yFO
  - gradlew.bat assemble

test_script:
  - gradlew.bat test

artifacts:
  - path: app/build/outputs/apk
    name: apk
    type: zip
  - path: app/build/reports
    name: reports
    type: zip
  - path: app/build/test-results
    name: test results
    type: zip
    
deploy:
  tag: 'custom-build-v$(appveyor_build_version)'
  release: 'BetterBatteryStats custom build version $(appveyor_build_version)'
  description: 'Built from branch $(APPVEYOR_REPO_BRANCH) at $(APPVEYOR_REPO_COMMIT_TIMESTAMP).'
  
  provider: GitHub
  auth_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ # your encrypted token from GitHub
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    #appveyor_repo_tag: true        # deploy on tag push only

notifications:
  - provider: Slack
    on_build_success: true
    on_build_failure: true
    incoming_webhook:
      secure: +5y63VhkKwOZVK264xwgH8gp7vI2cJivXvseQeSoYYNyH3wjOtid8Qz+gyNOjCGpI/xqxxJNwqFrL75ZPHYOYEKs9WhBWznTsFpJUAs5hxn1kcczMv6WYuwUzXJNEdqX6m47PnS7xrzUZJIRWNQCHRJCtN5VX+hXfVV6BT+tKQdRDeRr/LANhRLr2pAbIOGP
