environment:
  matrix:
    - ANDROID_HOME: 'C:\android-sdk-windows'

install:
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
  - 7z x sdk-tools-windows-4333796.zip -oC:\android-sdk-windows > nul
  - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses

build_script:
  - cmd: KEYSTORE_RELEASE=publicKeyStore.jks
  - cmd: KEYSTORE_DEBUG=%KEYSTORE_RELEASE%
  - cmd: KEYSTORE_PASSWORD=YiBODrehfLo37Mm5f3BFMASXRawiWXMj23RDZRRqBFul7TCvyWbqA2oeRR26CbIAnxiivjfWKyjP5aEbzabImmthxjNmewVUztP2sDyRuLPHjWnBYFzSwclAUecDxL8Vs5iOb2ds1h8XzfRFyOfKLZYrlsF9FI6AX10nspgcHs92Y28DoiN44hGkuLnPBk0PcEbeEsy5c3iWCz2bNolkdcjCaNJAZgjUUY48OyC9aJIujAFb4fNavxq24tznW70G63X6cRbuf0bhXtzVL2g39FXuhCKERcgu5dCbgp554mJbw2nL7XK7bK71HMkeBHk00huRSxN6hAKpd6uM2v65Ywd79lc42WHCaafPmoYTosBTvJSIcAKF64gpZCjCKCH6XwJyqAY3Mbp1T1QXyKor7WTvQmkF6Bjxux3TV3q4rf3roSbc96d2Qpy5hBWo0MiHNbFL0U9UwFJXzo0xXxNeFB2i285mq1kBBOvIEeYhsLhkGwX6craNEZu3DzjeHZRS
  - cmd: KEY_ALIAS=publicKey
  - cmd: KEY_PASSWORD=Xmg4oe1rydYZvIlDLzY5OSFDJkf2zIJcXhclCy0SeqMzGchDOsZf4w4AJANzC5D2LVltlF0onOQkBetHKMW5uEsbyFoZOVT9RhZr7NuTtafBLAVK1XDokHbCfQwUxqp2yGsnEyG8WU0fu8BRtdhce58KkoqrWuaA3uSb6h5IOjXU8TOhu1xcyHQ6IVDrsipK3FjLEU1u2rOY6ZZcaRNuYWQYWFh7DppXSYvhAxD23ckXqpyaVqHHHFyeV1SQTnp2oXIxB3jiyKETIlQN8z4gWyly05r8ZP84MrCE2dOt3buR0H5yIR6RPqVQc21B4tBKvk5g1NxT5qASaOFSRwMrCdd6B9rfmlX6iGtGLfaSRbGCeVzJOsMynps3U25IJ2S6UBD8eifCriyi9R3zmEhk6c46JBVfnZLRTQpDE1XobS7lCvf2t2aGW94ecBL6OILr9YaY9hEbEvD1JJegHjXepV74Hc19yAOS44WMBngWg79KHn4pvTnhffbH2bui3yFO
  - gradlew.bat assemble

test_script:
  - gradlew.bat test
